# Site settings
title: MEI Guidelines
email: info@music-encoding.org
baseurl: "" 
url: "http://guidelines.music-encoding.org"
style_baseurl: "https://music-encoding.github.io"
twitter_username: music-encoding
github: [metadata]

# Build settings
markdown: kramdown

exclude: [tools]

plugins:
  - jekyll-redirect-from

collections:
  guidelines-v3:
    output: false
  guidelines-dev:
    output: false

sidebar:  
    - id: s1
      content: 
          - id: guidelines
            label: 'Guidelines'
            url: 'guidelines'
          - id: elements
            label: 'Elements'
            url: 'elements'
          - id: attributeclasses
            label: 'Attribute Classes'
            url: 'attribute-classes'
          - id: modelclasses
            label: 'Model Classes'
            url: 'model-classes'
          - id: datatypes
            label: 'Data Types'
            url: 'data-types'