# Site settings
title: MEI Guidelines
email: info@music-encoding.org
baseurl: "/guidelines" 
url: "http://guidelines.music-encoding.org"
#style_baseurl: "https://music-encoding.github.io"
style_baseurl: "http://localhost:4001"
twitter_username: music-encoding
github: [metadata]


# Github repository used for Github edit button.
repository: "music-encoding/guidelines"

# path fragment to get to branch for files on github:
github_edit_path: "blob/master"

# Build settings
markdown: kramdown

exclude: [tools]

plugins:
  - jekyll-redirect-from

collections:
  guidelines-dev:
    output: false
    
tipue_search:
  include:
    collections: [guidelines-dev]

sidebar:  
    - id: s1
      content: 
          - id: guidelines
            label: 'Guidelines'
            url: 'guidelines/'
          - id: elements
            label: 'Elements'
            url: 'elements.html'
          - id: attributeclasses
            label: 'Attribute Classes'
            url: 'attribute-classes.html'
          - id: modelclasses
            label: 'Model Classes'
            url: 'model-classes.html'
          - id: datatypes
            label: 'Data Types'
            url: 'data-types.html'